# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Patrick Finn Horve"
description: "Professional site for Patrick Finn Horve"
baseurl: "/page" # the subpath of your site, e.g. "/blog"
url: "https://phorve.github.io"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax:
  enable: true
#  combo: "tex-mml-chtml"
#  tags: "none"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
    # Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/PatrickHorve
    icon: fab fa-twitter-square
