# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Patrick Finn Horve"
url: "https://phorve.github.io"
baseurl: "https://patrickfhorve.com"
date_format: "%B %-d, %Y"
#  combo: "tex-mml-chtml"
#  tags: "none"

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/PatrickHorve
    icon: fab fa-twitter-square
